import { defineConfig, type Plugin } from 'vite';
import { resolve } from 'path';
import { readdirSync, existsSync, statSync, readFileSync } from 'fs';
import { Marked, type Tokens } from 'marked';

// Dynamically find all trail page directories (index.html and climate.html)
function getTrailInputs(): Record<string, string> {
  const trailsDir = resolve(__dirname, 'src/web/trails');
  const inputs: Record<string, string> = {};

  if (!existsSync(trailsDir)) return inputs;

  const entries = readdirSync(trailsDir);
  for (const entry of entries) {
    const entryPath = resolve(trailsDir, entry);
    if (statSync(entryPath).isDirectory()) {
      // Add index.html if it exists
      const indexPath = resolve(entryPath, 'index.html');
      if (existsSync(indexPath)) {
        inputs[`trail-${entry}`] = indexPath;
      }
      // Add climate.html if it exists
      const climatePath = resolve(entryPath, 'climate.html');
      if (existsSync(climatePath)) {
        inputs[`trail-${entry}-climate`] = climatePath;
      }
      // Add plan.html if it exists
      const planPath = resolve(entryPath, 'plan.html');
      if (existsSync(planPath)) {
        inputs[`trail-${entry}-plan`] = planPath;
      }
    }
  }

  return inputs;
}

// Renders docs/gpx-import.md (the user-facing spec of the import pipeline)
// into how-import-works.html, replacing the <!--gpx-import-doc--> placeholder.
// The markdown stays the single source of truth; headings get GitHub-style
// ids so #anchors written against the doc keep working on the page.
function gpxImportDocPlugin(): Plugin {
  const render = () => {
    const md = readFileSync(resolve(__dirname, 'docs/gpx-import.md'), 'utf-8');
    const marked = new Marked({
      renderer: {
        heading({ tokens, depth, text }: Tokens.Heading) {
          const id = text
            .toLowerCase()
            .replace(/[^\w\s-]/g, '')
            .trim()
            .replace(/\s+/g, '-');
          return `<h${depth} id="${id}">${this.parser.parseInline(tokens)}</h${depth}>\n`;
        },
      },
    });
    return marked.parse(md) as string;
  };

  return {
    name: 'gpx-import-doc',
    transformIndexHtml: {
      order: 'pre',
      handler(html, ctx) {
        if (!ctx.filename.endsWith('how-import-works.html')) return html;
        return html.replace('<!--gpx-import-doc-->', render());
      },
    },
  };
}

export default defineConfig({
  root: 'src/web',
  base: './',
  publicDir: '../../public',
  server: {
    fs: {
      // Allow serving files from the data directory
      allow: ['../..'],
    },
  },
  plugins: [gpxImportDocPlugin()],
  build: {
    outDir: '../../dist',
    emptyOutDir: true,
    rollupOptions: {
      input: {
        main: resolve(__dirname, 'src/web/index.html'),
        // User GPX import pages. These sit at the top level of src/web on
        // purpose: src/web/trails/<id>/ is gitignored and regenerated by
        // build:trails, so anything hand-written there would be transient.
        upload: resolve(__dirname, 'src/web/upload.html'),
        'how-import-works': resolve(__dirname, 'src/web/how-import-works.html'),
        'my-trail': resolve(__dirname, 'src/web/my-trail.html'),
        'my-plan': resolve(__dirname, 'src/web/my-plan.html'),
        // Dynamically include all generated trail pages
        ...getTrailInputs(),
      },
    },
  },
  resolve: {
    alias: {
      '@lib': resolve(__dirname, 'src/lib'),
    },
  },
});
