/**
 * Waypoint type → marker glyph.
 *
 * The guide map draws each waypoint as a white badge with a category-coloured
 * ring (see GuideMap) and one of these ink glyphs on top, FarOut-style, so a
 * marker is identifiable without reading its label.
 *
 * The glyphs are committed PNGs (`assets/map-icons/`, generated by
 * `scripts/build-map-icons.mjs`) rather than an icon font or emoji: the map has
 * to work fully offline, and the bundled glyph pbfs cover Latin + punctuation
 * only — no pictographs — so a symbol layer `textField` cannot draw iconography.
 *
 * Two mappings live here: `waypointIconName` for curated waypoint `type`
 * strings, and `poiIconName` for the six OpenStreetMap POI categories the map's
 * POI layer draws. They share one glyph set — a POI and a waypoint of the same
 * kind should look the same; the POI markers are told apart by the smaller,
 * category-tinted badge GuideMap draws underneath, not by the ink.
 *
 * Pure + React-free so the grouping is unit-testable; the image registry lives
 * next door in `waypoint-icon-images.ts`.
 */

import { baseWaypointType } from '@lib/waypoint-taxonomy';

/** The shipped glyph set. Each name maps 1:1 to `assets/map-icons/<name>.png`. */
export const WAYPOINT_ICON_NAMES = [
  'water',
  'water-tank',
  'campsite',
  'hut',
  'bed',
  'town',
  'resupply',
  'trailhead',
  'endpoint',
  'junction',
  'milestone',
  'gap',
  'note',
  'road',
  'ford',
  'summit',
  'hazard',
  'info',
  'beach',
  'restaurant',
  'transport',
  'emergency',
  'poi',
] as const;

export type WaypointIconName = (typeof WAYPOINT_ICON_NAMES)[number];

/** Glyph used for any type not listed below (and for `poi` itself). */
export const FALLBACK_WAYPOINT_ICON: WaypointIconName = 'poi';

/**
 * Bundled `type` strings → glyph. Types the six bundled trails actually use are
 * marked; the rest come from the waypoint classifier's vocabulary and are
 * grouped onto the nearest shipped glyph so a data update never falls all the
 * way through to the generic dot.
 */
const TYPE_TO_ICON: Record<string, WaypointIconName> = {
  // Water sources
  water: 'water', // in data
  spring: 'water',
  creek: 'water',
  stream: 'water',
  river: 'water',
  tap: 'water',
  'water-tank': 'water-tank', // in data
  tank: 'water-tank',
  rainwater: 'water-tank',

  // Camping
  campsite: 'campsite', // in data
  camp: 'campsite',
  campground: 'campsite',
  camping: 'campsite',

  // Roofed shelter
  hut: 'hut', // in data
  shelter: 'hut',

  // Beds you pay for
  accommodation: 'bed', // in data
  'caravan-park': 'bed', // in data
  hostel: 'bed',
  hotel: 'bed',
  motel: 'bed',

  // Towns and supplies
  town: 'town', // in data
  resupply: 'resupply', // in data
  food: 'resupply', // in data
  store: 'resupply',
  shop: 'resupply',
  supermarket: 'resupply',
  'post-office': 'resupply',

  // Meals out (shared with the `restaurant` POI category)
  restaurant: 'restaurant',
  cafe: 'restaurant',
  pub: 'restaurant',

  // Trail ends
  trailhead: 'trailhead', // in data
  endpoint: 'endpoint', // in data
  terminus: 'endpoint',
  start: 'endpoint',
  finish: 'endpoint',

  // Navigation features
  junction: 'junction', // in data (CDT alternate branch/rejoin points)
  milestone: 'milestone', // in data (the CDT's every-10-mile markers)
  milepost: 'milestone',
  marker: 'milestone',
  fork: 'junction',
  gate: 'junction',
  stile: 'junction',
  road: 'road',
  'road-crossing': 'road', // in data
  highway: 'road',
  parking: 'road',
  'car-park': 'road',

  // Public transport (shared with the `transport` POI category)
  'bus-stop': 'transport',
  station: 'transport',
  ferry: 'transport',

  // Wet crossings
  'inlet-crossing': 'ford', // in data
  ford: 'ford',
  'river-crossing': 'ford',
  'creek-crossing': 'ford',
  bridge: 'ford',

  // Views
  lookout: 'summit',
  summit: 'summit',
  peak: 'summit',
  viewpoint: 'summit',
  view: 'summit',

  // Warnings and notices
  hazard: 'hazard',
  danger: 'hazard',
  warning: 'hazard',
  information: 'info',
  info: 'info',
  sign: 'info',

  // Coast
  beach: 'beach', // in data

  // Curated third-party vocabulary the bundled data can carry (the CDT build's
  // Ley map-set and 2018-walk files). Listed so they get their own ink rather
  // than the generic dot; `camp-2018` deliberately shares the campsite glyph,
  // because that is what it is.
  gap: 'gap',
  'ley-note': 'note',
  'ley-waypoint': 'info',
  'camp-2018': 'campsite',

  // Generic
  poi: 'poi', // in data
  waypoint: 'poi', // in data
  other: 'poi',
};

/** The glyph for a waypoint type (generic point-of-interest for unknowns). */
export function waypointIconName(type: string): WaypointIconName {
  // A turn-off shows the icon of the place it serves: `hut-access` is the hut.
  return TYPE_TO_ICON[type] ?? TYPE_TO_ICON[baseWaypointType(type)] ?? FALLBACK_WAYPOINT_ICON;
}

/**
 * `TrailPOICategory` → glyph. Takes a plain `string` rather than the union so
 * a trail JSON carrying a category this build does not know about still gets a
 * marker instead of an invisible one (an `icon` naming an unregistered image
 * draws nothing at all).
 */
const POI_CATEGORY_TO_ICON: Record<string, WaypointIconName> = {
  water: 'water',
  camping: 'campsite',
  resupply: 'resupply',
  restaurant: 'restaurant',
  transport: 'transport',
  emergency: 'emergency',
};

/** The glyph for an OpenStreetMap POI category. */
export function poiIconName(category: string): WaypointIconName {
  return POI_CATEGORY_TO_ICON[category] ?? FALLBACK_WAYPOINT_ICON;
}
